Associatedtype Payload for Observable Protocol
wordpress-mobile/WordPressFlux-iOS pull request #4
Opened 2019-06-12 09:57 UTC by danielebogo

This PR uses an `associatedtype` to set a generic Payload with the protocol Dispatcher.
Set a generic Payload allows me to:
• Keep the compatibility with the current implementation if its value is _Void_
```
viewModel.onChange {
...
}
```
• Get the Payload as closure argument
```
viewModel.onChange { payload in
...
}
```

2019-06-12 10:37 UTC, koke commented
Do you have a use case for it? It seems like a good addition, but looking at this feels like it's something I initially tried and discarded, but I can't remember why right now.

I'm guessing it had something to do with overcomplicating the API. But there have also been a few Swift releases in between, so maybe what I wanted wasn't possible back then without a lot of boilerplate.

2019-06-12 14:57 UTC, aerych commented
Love the timing of this. :) Last week I was wanting to be able to include payloads when emitting a change so Monday I wrote an "EventfulStore" with an `onChangeEvent` method to do the trick. I had a TODO to look at how best to add it back to the flux pod.  But you've beat me to it and this looks much nicer.

2019-06-12 18:49 UTC, aerych approved these changes
Changes look good and tests pass.  I'll give it my :+1: but curious if @koke has any other thoughts.

2019-06-13 07:43 UTC, danielebogo commented
@koke the main reason is to pass the payload as closure argument and have something like this:
```
receipt = viewModel.onChange { state in
            switch state {
            case .loading, .stationary:
                // loading
                break
            case .completed(let success, let sections):
               // completed
                break
            }
        }
```
Otherwise I need to have always a reference of the same _viewModel_ in the closure and expose the payload property like this:
```
receipt = viewModel.onChange { [unowned self] in
            switch self.viewModel.state {
            case .loading, .stationary:
                // loading
                break
            case .completed(let success, let sections):
                // completed
                break
            }
        }
```
I found that using the `associatedtype` is more _elegant_ and it allows me to use both the cases depending on the Payload value defined by the `Dispatcher<Payload>` implementation, which is mandatory.

(I'm in love with this library 😄)

2019-06-14 15:27 UTC, koke commented
> Last week I was wanting to be able to include payloads when emitting a change so Monday I wrote an "EventfulStore" with an onChangeEvent method to do the trick

@aerych I've been looking at that, and I don't fully understand what it's doing yet, but from what I did understand, you should probably just be using the global ActionDispatcher instead of a custom store subclass.

2019-06-14 15:52 UTC, koke requested changes
We chatted on Slack, but I'll summarize my review here.

I don't think this is a good addition to `Observable`. When I observe an Observable, I'm asking to be notified when that object changes. Allowing a Payload in the handler other than the object itself isn't consistent with the pattern, and it might get called without the payload having changed.

I understand that it's a nicer syntax to avoid having to capture the observed thing, but it doesn't feel like enough of a reason to change the design.

I think your use case could be approached by mapping the observable. This need some better naming of generic types, and I have only tested that it compiles, but it should work:

```swift
public struct MappingObservable<O: Observable,T>: Observable {
    public var changeDispatcher: Dispatcher<Void> {
        return target.changeDispatcher
    }

    let target: O
    let transform: (O) -> T

    public init(target: O, transform: @escaping (O) -> T) {
        self.target = target
        self.transform = transform
    }

    public func onChange(_ handler: @escaping () -> Void) -> Receipt {
        return target.onChange(handler)
    }

    public func onChange(_ handler: @escaping (T) -> Void) -> Receipt {
        return target.onChange({ handler(self.transform(self.target))})
    }

    public func emitChange() {
        target.emitChange()
    }
}

extension Observable {
    func map<T>(_ transform: @escaping (Self) -> T) -> MappingObservable<Self, T> {
        return MappingObservable(target: self, transform: transform)
    }
}
```

Then you can just map your regular Observable and have the extra `onChange` event with the property as a payload:

```swift
enum JetpackRemoteInstallState {
    case install
    case installing
    case failure
    case success
}

class JetpackRemoteInstallViewModel: Observable {
    let changeDispatcher = Dispatcher<Void>()

    private(set) var state: JetpackRemoteInstallState = .install {
        didSet {
            emitChange()
        }
    }

    init() {
    }
}

let viewModel = JetpackRemoteInstallViewModel()
_ = viewModel.onChange {
    // No arguments passed
}
_ = viewModel.map( { $0.state }).onChange { (state) in
    // state passed
}
```

2019-06-14 15:54 UTC, koke commented
I think there was some fancy new Swift syntax that could turn ```viewModel.map( { $0.state })``` into ```viewModel.map(\.state)```, but I haven't caught up with all the new things in the last year 😞

2019-06-14 16:10 UTC, koke commented
Ah yes, it's possible as well:

```swift
extension Observable {
    func map<T>(_ keyPath: KeyPath<Self, T>) -> MappingObservable<Self, T> {
        return map({ target in target[keyPath: keyPath] })
    }
}
```

```swift
_ = viewModel.map(\.state).onChange { (state) in
    // same but with key path
}
```

2019-06-18 08:43 UTC, danielebogo commented
Hey @koke I'm going to close this PR following our Slack conversation. I totally agree with the fact that the _Observable_ should remain immutable and that the only change we can do is passing Self as Payload in the closure.

2019-06-18 08:43 UTC, closed without merging